theme: jekyll-theme-minimal
title: Artisan Adaptations
description: Custom adaptive devices with an eye for individualized needs designed by a Certified Occupational Therapy Assistant with a passion for accessibility and electronics.
theme: minima

github_username: artisanadaptations

show_excerpts: false
